# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Build and Publish Docker image

#on:
    #workflow_run:
        #workflows: [Upload Python Package]
        #types:
          #- completed

on:
  release:
    types: [published]
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  push_to_registry:  
    name: Push Docker image to multiple registries
    
    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      contents: read
      
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract version
        id: extract_version
        run: |
          head_branch="${{ github.event.workflow_run.head_branch }}"

          # Extract version from head_branch
          version_from_head_branch=$(echo "$head_branch" | sed 's/[^0-9.]*//g')          
          major=$(echo "$version_from_head_branch" | cut -d '.' -f 1)
          minor=$(echo "$version_from_head_branch" | cut -d '.' -f 2)
          major_minor=$(echo "$major.$minor")

          # Output the results
          echo "Version from head_branch: $version_from_head_branch"
          echo "VERSION=$version_from_head_branch" >> $GITHUB_OUTPUT
          echo "MAJOR=$major" >> $GITHUB_OUTPUT
          echo "MINOR=$minor" >> $GITHUB_OUTPUT
          echo "MAJOR_MINOR=$major_minor" >> $GITHUB_OUTPUT

        # Now you can use ${{ steps.extract_version.outputs.version_from_display_title }} and ${{ steps.extract_version.outputs.version_from_head_branch }} in subsequent steps.
        
        #- name: Extract version
          #id: extract_version
          #run: |
            #version_from_head_branch=$(echo "${{ github.event.head_commit.message }}" | grep -oP '(?<=^v?)[0-9]+\.[0-9]+\.[0-9]+')
            #major=$(echo "$version_from_head_branch" | cut -d '.' -f 1)
            #minor=$(echo "$version_from_head_branch" | cut -d '.' -f 2)
            #echo "::set-output name=version::$version_from_head_branch"
            #echo "::set-output name=major::$major"
            #echo "::set-output name=minor::$minor"
        
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ github.repository }}
            ghcr.io/${{ github.repository }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,value=latest,enable=true

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
          
      - name: Build and push Docker images
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          #tags: "latest,${{ steps.pre-step.outputs.release-version }}, 
          #tags: | 
            #${{ github.repository }}:latest
            #latest
            #${{ steps.meta.outputs.tags }}
            #${{ steps.extract_version1.outputs.version }}
            #${{ steps.extract_version.outputs.version_from_display_title }}            
            #${{ steps.extract_version.outputs.version_from_head_branch }}
          #tags: ${{ steps.meta.outputs.tags }}
          tags: |    
            ${{ steps.meta.outputs.tags }}
            ${{ github.repository }}:${{ steps.extract_version.outputs.VERSION }}
            ${{ github.repository }}:${{ steps.extract_version.outputs.MAJOR_MINOR }}
            ghcr.io/${{ github.repository }}:${{ steps.extract_version.outputs.VERSION }}
            ghcr.io/${{ github.repository }}:${{ steps.extract_version.outputs.MAJOR_MINOR }}
          labels: ${{ steps.meta.outputs.labels }}
